name: testeable
version: 1.0.0
description: A basic starter application template for Angel3 framework
publish_to: none
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  angel3_auth: ^8.0.0
  angel3_configuration: ^8.0.0
  angel3_framework: ^8.1.1
  angel3_production: ^8.0.0
  angel3_static: ^8.0.0
  angel3_validate: ^8.0.0
  angel3_websocket: ^8.0.0
  belatuk_pretty_logging: ^6.0.0
dev_dependencies:
  angel3_hot: ^8.0.0
  io: ^1.0.4
  test: ^1.24.8
  lints: ^3.0.0




